const transportTypes = [["plane","飞机"],["train","火车"],["bus","大巴"],["boat","船"],["car","车"]];
const params = new URLSearchParams(location.search);
const roomId = params.get("room") || Array.from(crypto.getRandomValues(new Uint8Array(4))).map((v)=>v.toString(16).padStart(2,"0")).join("").toUpperCase();
const storageKey = `trip-planner-library:${roomId}`;
const legacyStorageKey = `trip-planner:${roomId}`;
const clientKey = "trip-planner:client-id";
const nameKey = "trip-planner:member-name";
const clientId = localStorage.getItem(clientKey) || crypto.randomUUID();
localStorage.setItem(clientKey, clientId);
const channel = "BroadcastChannel" in window ? new BroadcastChannel(storageKey) : null;
let library = loadLibrary();
let ws, wsReady = false, revision = 0, applying = false, saveFallbackTimer = 0;
let membersOnline = new Map();
let selectedActivityId = "";
let selectedContext = { type: "day", dayId: "", activityId: "", field: "" };
const collapsedDays = new Set();
let drag = null;
let mapScope = "list";
let aiItems = [];
const $ = (s, r = document) => r.querySelector(s);
const $$ = (s, r = document) => [...r.querySelectorAll(s)];
const els = {
  title: $("#tripTitle"), start: $("#startDate"), origin: $("#originCity"), member: $("#memberName"), members: $("#memberStrip"),
  room: $("#roomCode"), lists: $("#tripList"), addList: $("#addListBtn"), listName: $("#listNameInput"), dayLimit: $("#dayLimitInput"), dayLimitValue: $("#dayLimitValue"),
  dayCount: $("#dayCount"), activityCount: $("#activityCount"), stayCount: $("#stayCount"), transportSummary: $("#transportSummary"), dayList: $("#dayList"),
  addDay: $("#addDayBtn"), addDayTop: $("#addDayTopBtn"), syncState: $("#syncState"), syncText: $("#syncText"), copy: $("#copyLinkBtn"), detailLabel: $("#detailLabel"),
  delDay: $("#deleteDayBtn"), loc: $("#detailLocation"), stay: $("#detailStay"), tabs: $("#transportTabs"), from: $("#transportFrom"), to: $("#transportTo"),
  depart: $("#transportDepart"), arrive: $("#transportArrive"), form: $("#activityForm"), submitText: $("#activitySubmitText"),
  cancel: $("#cancelEditActivityBtn"), clearTransport: $("#clearTransportBtn"), time: $("#activityTime"), place: $("#activityPlace"), activityTitle: $("#activityTitle"), note: $("#activityNote"), toast: $("#toast")
};
init();

function init(){ ensureRoom(); if(!localStorage.getItem(nameKey)) localStorage.setItem(nameKey,"我"); exposeStore(); bind(); render(); connect(); fetchRoomState(); }
function now(){ return Date.now(); }
function today(){ const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000); return d.toISOString().slice(0,10); }
function blankTrip(name="新行程单"){ const t=now(); const day={id:crypto.randomUUID(),location:"",stay:"",activities:[],updatedAt:t,orderUpdatedAt:t}; return {version:1,tripTitle:name,startDate:today(),originCity:"",selectedDayId:day.id,dayLimit:30,updatedAt:t,orderUpdatedAt:t,days:[day],budget:{currency:"CNY",items:{},limit:0,updatedAt:t}}; }
function makeList(name="新行程单", trip=blankTrip(name)){ const t=now(); trip.tripTitle ||= name; trip.selectedDayId ||= trip.days?.[0]?.id || ""; return {id:crypto.randomUUID(),name,trip,createdAt:t,updatedAt:t}; }
function loadLibrary(){
  try{ const v=JSON.parse(localStorage.getItem(storageKey)); if(v?.lists?.length) return normLib(v); }catch{ localStorage.removeItem(storageKey); }
  try{ const v=JSON.parse(localStorage.getItem(legacyStorageKey)); if(v?.days?.length) return normLib({version:2,activeListId:"",lists:[makeList(v.tripTitle||"我的行程单",v)],updatedAt:now()}); }catch{}
  const l=makeList("新行程单"); return normLib({version:2,activeListId:l.id,members:[],lists:[l],deleted:emptyDeleted(),updatedAt:now()});
}
function normLib(input={}){ const t=now(); const lists=(input.lists||[]).filter(x=>x?.trip?.days?.length).map((l,i)=>{ l={...l}; l.id ||= crypto.randomUUID(); l.trip=normTrip(l.trip); l.name=(l.name||l.trip.tripTitle||`行程单 ${i+1}`).trim(); l.trip.tripTitle ||= l.name; l.updatedAt ||= l.trip.updatedAt||t; l.createdAt ||= t; return l; }); if(!lists.length) lists.push(makeList()); return {version:2,activeListId:lists.some(l=>l.id===input.activeListId)?input.activeListId:lists[0].id,members:normMembers(input.members),lists,deleted:normDeleted(input.deleted),updatedAt:input.updatedAt||t}; }
function normMembers(ms=[]){ const seen=new Set(); return (Array.isArray(ms)?ms:[]).map(m=>({id:m?.id||crypto.randomUUID(),name:String(m?.name||"").trim(),createdAt:m?.createdAt||now(),updatedAt:m?.updatedAt||now()})).filter(m=>m.name&&!seen.has(m.id)&&seen.add(m.id)); }
function normTrip(t={}){ const days=(t.days||[]).map(normDay).filter(Boolean); const budget=t.budget&&typeof t.budget==="object"?t.budget:{}; return {...t,tripTitle:t.tripTitle||"新行程单",startDate:t.startDate||today(),originCity:t.originCity||"",selectedDayId:t.selectedDayId||days[0]?.id||"",dayLimit:Math.max(days.length||1,Math.min(60,Number(t.dayLimit)||30)),updatedAt:t.updatedAt||now(),orderUpdatedAt:t.orderUpdatedAt||t.updatedAt||now(),budget:{...budget,currency:budget.currency||"CNY",items:budget.items||{},updatedAt:budget.updatedAt||t.updatedAt||now()},days:days.length?days:blankTrip(t.tripTitle).days}; }
function normDay(d={}){ return {id:d.id||crypto.randomUUID(),location:d.location||"",stay:d.stay||"",updatedAt:d.updatedAt||now(),orderUpdatedAt:d.orderUpdatedAt||d.updatedAt||now(),activities:(d.activities||[]).map(normAct)}; }
function normAct(a={}){ return {id:a.id||crypto.randomUUID(),time:a.time||"",title:a.title||"未命名事项",place:a.place||"",note:a.note||"",tags:Array.isArray(a.tags)?a.tags:[],done:Boolean(a.done),budget:a.budget||null,transport:normTransport(a.transport),updatedAt:a.updatedAt||now()}; }
function normTransport(t){ if(!t||typeof t!=="object") return null; const n={type:t.type||"",from:t.from||"",to:t.to||"",depart:t.depart||"",arrive:t.arrive||""}; if(!Object.values(n).some(Boolean)) return null; if(!transportTypes.some(([id])=>id===n.type)) n.type="car"; return n; }
function emptyDeleted(){ return {lists:{},days:{},activities:{},members:{}}; }
function normDeleted(d={}){ return {lists:{...(d.lists||{})},days:{...(d.days||{})},activities:{...(d.activities||{})},members:{...(d.members||{})}}; }
function markDeleted(kind,id){ if(!id) return; library.deleted ||= emptyDeleted(); library.deleted[kind] ||= {}; library.deleted[kind][id]=now(); }
function touch(x){ if(x) x.updatedAt=now(); return x; }
function touchOrder(x){ if(x) x.orderUpdatedAt=now(); return touch(x); }
function activeList(){ return library.lists.find(l=>l.id===library.activeListId)||library.lists[0]; }
function trip(){ return activeList().trip; }
function selectedDay(){ return trip().days.find(d=>d.id===trip().selectedDayId)||trip().days[0]; }
function dayDate(i){ const d=new Date(`${trip().startDate}T00:00:00`); d.setDate(d.getDate()+i); return d; }

function bind(){
  els.title.oninput=()=>updateTrip({tripTitle:els.title.value}); els.start.onchange=()=>updateTrip({startDate:els.start.value}); els.origin.oninput=()=>updateTrip({originCity:els.origin.value});
  els.dayLimit.oninput=()=>{ trip().dayLimit=Math.max(trip().days.length,Number(els.dayLimit.value)||30); touch(trip()); save("day-limit"); render(); };
  els.addList.onclick=()=>{ const l=makeList(`新行程单 ${library.lists.length+1}`); library.lists.push(l); library.activeListId=l.id; touch(library); save("add-list"); render(); els.listName.focus(); };
  els.listName.oninput=()=>{ const l=activeList(); l.name=els.listName.value.trim()||"未命名行程单"; l.trip.tripTitle=l.name; touch(l); touch(l.trip); save("rename-list"); renderLists(); };
  els.member.oninput=()=>{ localStorage.setItem(nameKey,els.member.value.trim()||"我"); announce(); };
  els.addDay.onclick=els.addDayTop.onclick=addDay; els.delDay.onclick=()=>deleteDay(selectedDay()?.id); els.copy.onclick=copyLink;
  els.loc.oninput=()=>{ const d=selectedDay(); d.location=els.loc.value; touch(d); save("day-location"); renderLight(); };
  els.stay.oninput=()=>{ const d=selectedDay(); d.stay=els.stay.value; touch(d); save("day-stay"); renderLight(); };
  els.clearTransport.onclick=()=>{ els.tabs.dataset.type=""; els.from.value=els.to.value=els.depart.value=els.arrive.value=""; renderTabs(); };
  els.cancel.onclick=()=>resetForm(); els.form.onsubmit=saveActivity;
  channel?.addEventListener("message",e=>{ if(e.data?.type!=="library"||e.data.clientId===clientId) return; applyRemote(e.data.library,"同浏览器标签页已同步",false,e.data.revision); });
  window.addEventListener("beforeunload",()=>send({type:"leave",clientId}));
  document.addEventListener("click", handleSelectionClick, true);
}

function render(){ const t=trip(), l=activeList(); els.title.value=t.tripTitle; els.start.value=t.startDate; els.origin.value=t.originCity||""; els.member.value=localStorage.getItem(nameKey)||"我"; els.listName.value=l.name; els.room.textContent=roomId; els.dayLimit.value=t.dayLimit; els.dayLimitValue.textContent=`${t.dayLimit} 天`; renderTabs(); ensurePanels(); renderLists(); renderStats(); renderMembers(); renderDays(); renderDetail(); renderSmart(); markSelectedDom(); }
function renderLight(){ renderStats(); renderDays(); renderDetail(); renderSmart(); markSelectedDom(); }
function renderLists(){ els.lists.replaceChildren(...library.lists.map(l=>{ const row=document.createElement("div"); row.className=`trip-list-row ${l.id===library.activeListId?"active":""} ${isConflictBackup(l)?"historical-backup":""}`; const count=l.trip.days.reduce((s,d)=>s+d.activities.length,0); row.innerHTML=`<button class="trip-list-item ${l.id===library.activeListId?"active":""}" type="button"><span class="trip-list-name">${esc(cleanBackupName(l.name))}</span><span class="trip-list-meta">${isConflictBackup(l)?"历史备份 · ":""}${l.trip.days.length} 天 · ${count} 项</span></button><button class="trip-list-delete" type="button" title="删除行程单" ${library.lists.length<=1?"disabled":""}>×</button>`; $(".trip-list-item",row).onclick=()=>{ library.activeListId=l.id; mapScope="list"; render(); }; $(".trip-list-delete",row).onclick=()=>deleteList(l.id); return row; })); }
function isConflictBackup(l){ return /^冲突备份/.test(String(l.name||"")); }
function cleanBackupName(name){ return String(name||"").replace(/^(冲突备份 -\s*)+/g,"历史备份 - "); }
function renderStats(){ const t=trip(), acts=t.days.flatMap(d=>d.activities); els.dayCount.textContent=`${t.days.length} / ${t.dayLimit} 天`; els.activityCount.textContent=acts.length; els.stayCount.textContent=t.days.filter(d=>d.stay.trim()).length; els.transportSummary.replaceChildren(...transportTypes.map(([id,label])=>[label,acts.filter(a=>a.transport?.type===id).length]).filter(([,n])=>n).map(([label,n])=>pill(`${label} ${n}`))); }
function renderMembers(){ const frag=document.createDocumentFragment(); const managed=document.createElement("div"); managed.className="managed-members"; (library.members||[]).forEach(m=>{ const node=document.createElement("label"); node.className="managed-member"; node.innerHTML=`<span class="avatar">${esc(m.name[0]||"?")}</span><input value="${esc(m.name)}" aria-label="修改同行人"><button class="member-delete" type="button">×</button>`; $("input",node).onchange=e=>{ m.name=e.target.value.trim()||"未命名"; touch(m); save("rename-member"); renderMembers(); }; $("button",node).onclick=()=>{ markDeleted("members",m.id); library.members=library.members.filter(x=>x.id!==m.id); save("delete-member"); renderMembers(); }; managed.append(node); }); const add=document.createElement("button"); add.className="mini-action member-add-action"; add.type="button"; add.textContent="添加同行人"; add.onclick=()=>{ library.members=normMembers([...(library.members||[]),{name:els.member.value||"新同行人"}]); save("add-member"); renderMembers(); }; managed.append(add); frag.append(managed); els.members.replaceChildren(frag); }
function renderDays(){ const t=trip(); const visibleIds=new Set(t.days.map(d=>d.id)); [...collapsedDays].forEach(id=>{ if(!visibleIds.has(id)) collapsedDays.delete(id); }); els.addDay.disabled=els.addDayTop.disabled=t.days.length>=t.dayLimit; els.dayList.replaceChildren(...t.days.map((d,i)=>{ const isCollapsed=collapsedDays.has(d.id); const budget=dayBudgetText(d); const card=document.createElement("article"); card.className=`day-card day-card-compact ${d.id===t.selectedDayId?"active":""} ${isCollapsed?"is-collapsed":"is-expanded"}`; card.dataset.dayId=d.id; card.draggable=true; card.innerHTML=`<button class="day-main" type="button" aria-expanded="${!isCollapsed}"><span class="day-index">第 ${i+1} 天</span><span class="day-date">${new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric"}).format(dayDate(i))}</span><span class="day-weekday">${new Intl.DateTimeFormat("zh-CN",{weekday:"long"}).format(dayDate(i))}</span><span class="day-compact-location">城市 ${esc(d.location||"未填写地点")}</span><span class="day-compact-stay">住宿 ${esc(d.stay||"未填写")}</span><span class="day-compact-budget">${esc(budget)}</span><span class="day-compact-count">${d.activities.length} 项</span><span class="day-inline-actions"><button class="day-delete-inline" type="button" ${t.days.length<=1?"disabled":""}>×</button><span class="drag-handle day-drag-handle" draggable="true">⋮⋮</span></span></button><div class="day-content"><div class="day-meta"></div><div class="activity-list" data-day-id="${d.id}"></div></div>`; $(".day-main",card).onclick=e=>{ if(e.target.closest(".day-delete-inline,.drag-handle,.day-header-plus")) return; selectDay(d.id); if(t.selectedDayId===d.id){ if(collapsedDays.has(d.id)) collapsedDays.delete(d.id); else collapsedDays.add(d.id); } render(); }; $(".day-delete-inline",card).onclick=e=>{ e.stopPropagation(); deleteDay(d.id); }; const meta=$(".day-meta",card); meta.append(pill(`城市 ${d.location||"未填写地点"}`), pill(`住宿 ${d.stay||"未填写"}`), pill(budget)); const list=$(".activity-list",card); if(!d.activities.length){ const empty=document.createElement("div"); empty.className="empty-state"; empty.textContent="还没有事项"; list.append(empty); } else d.activities.forEach(a=>list.append(activityRow(d.id,a))); bindDrag(card); return card; })); }
function dayBudgetText(day){ const info=dayBudgetInfo(day); return info.total?`预算 ${formatBudget(info.total,info.currency)}`:"预算未估算"; }
function dayBudgetInfo(day){ const t=trip(), items=t.budget?.items||{}, fallbackCurrency=t.budget?.currency||"CNY"; const total=(day.activities||[]).reduce((sum,a)=>{ const item=items[a.id]; if(item&&Number.isFinite(Number(item.cost))) return sum+Number(item.cost); const own=a.budget||{}; const value=Number(own.amount??own.cost??0); return Number.isFinite(value)?sum+value:sum; },0); return {total,currency:fallbackCurrency}; }
function formatBudget(value,currency="CNY"){ const digits=currency==="CNY"||currency==="JPY"?0:2; try{ return new Intl.NumberFormat("zh-CN",{style:"currency",currency,minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value); }catch{ return `${currency} ${Math.round(value).toLocaleString("zh-CN")}`; } }
function activityRow(dayId,a){ const row=document.createElement("div"); row.className=`activity-row ${a.id===selectedActivityId?"editing":""}`; row.dataset.dayId=dayId; row.dataset.activityId=a.id; row.draggable=true; const tr=transportLabel(a.transport); row.innerHTML=`<span class="activity-time" data-select-field="time">${esc(a.time||"")}</span><span class="activity-body"><strong data-select-field="title">${esc(a.title)}</strong>${a.place?`<span data-select-field="place">${esc(a.place)}</span>`:""}${a.note?`<p data-select-field="note">${esc(a.note)}</p>`:""}${tr?`<button class="activity-transport-chip" data-select-field="transport" type="button">${esc(tr)}</button>`:`<button class="activity-transport-add" data-select-field="transport" type="button">添加交通</button>`}</span><span class="activity-actions"><button class="activity-drag-handle" type="button">⋮⋮</button><button class="edit-activity" type="button">✎</button><button class="remove-activity" type="button">×</button></span>`; $(".edit-activity",row).onclick=()=>{ selectActivity(dayId,a.id); loadActivity(dayId,a.id); }; $(".activity-transport-chip,.activity-transport-add",row).onclick=()=>{ selectField(dayId,a.id,"transport"); loadActivity(dayId,a.id,true); }; $(".remove-activity",row).onclick=()=>{ const d=trip().days.find(x=>x.id===dayId); markDeleted("activities",a.id); d.activities=d.activities.filter(x=>x.id!==a.id); touchOrder(d); save("delete-activity"); render(); }; bindDrag(row); return row; }
function renderDetail(){ const t=trip(), d=selectedDay(), i=t.days.findIndex(x=>x.id===d?.id); if(!d) return; els.detailLabel.textContent=`第 ${i+1} 天`; els.delDay.disabled=t.days.length<=1; if(document.activeElement!==els.loc) els.loc.value=d.location; if(document.activeElement!==els.stay) els.stay.value=d.stay; }
function renderTabs(){ const type=els.tabs.dataset.type||""; els.tabs.replaceChildren(...transportTypes.map(([id,label])=>{ const b=document.createElement("button"); b.className=`transport-tab ${type===id?"active":""}`; b.type="button"; b.textContent=label; b.onclick=()=>{ els.tabs.dataset.type=id; renderTabs(); }; return b; })); }
function saveActivity(e){ e.preventDefault(); const d=selectedDay(); const payload=normAct({id:selectedActivityId||crypto.randomUUID(),time:els.time.value,title:els.activityTitle.value.trim(),place:els.place.value.trim(),note:els.note.value.trim(),transport:{type:els.tabs.dataset.type,from:els.from.value.trim(),to:els.to.value.trim(),depart:els.depart.value,arrive:els.arrive.value},updatedAt:now()}); if(selectedActivityId){ const old=d.activities.find(a=>a.id===selectedActivityId); if(old) Object.assign(old,payload); } else d.activities.push(payload); touchOrder(d); selectedActivityId=""; resetForm(); save("save-activity"); render(); toast("事项已保存"); }
function loadActivity(dayId,id,focusTransport=false){ const t=trip(), d=t.days.find(x=>x.id===dayId), a=d?.activities.find(x=>x.id===id); if(!a) return; selectActivity(dayId,id); t.selectedDayId=dayId; selectedActivityId=id; els.time.value=a.time||""; els.place.value=a.place||""; els.activityTitle.value=a.title||""; els.note.value=a.note||""; els.tabs.dataset.type=a.transport?.type||""; els.from.value=a.transport?.from||""; els.to.value=a.transport?.to||""; els.depart.value=a.transport?.depart||""; els.arrive.value=a.transport?.arrive||""; renderTabs(); render(); requestAnimationFrame(()=> (focusTransport?els.from:els.activityTitle).focus()); }
function resetForm(){ selectedActivityId=""; els.form.reset(); els.tabs.dataset.type=""; renderTabs(); }
function updateTrip(p){ Object.assign(trip(),p); if(p.tripTitle!==undefined){ activeList().name=p.tripTitle.trim()||"未命名行程单"; touch(activeList()); } touch(trip()); save("update-trip"); renderLight(); renderLists(); }
function addDay(){ const t=trip(); if(t.days.length>=t.dayLimit) return toast("已达到天数上限"); const stamp=now(); const d={id:crypto.randomUUID(),location:"",stay:"",activities:[],updatedAt:stamp,orderUpdatedAt:stamp}; t.days.push(d); t.selectedDayId=d.id; touchOrder(t); save("add-day"); render(); }
function deleteDay(id){ const t=trip(); if(t.days.length<=1) return toast("至少保留一天"); const i=t.days.findIndex(d=>d.id===id); if(i<0) return; markDeleted("days",id); t.days[i].activities.forEach(a=>markDeleted("activities",a.id)); collapsedDays.delete(id); t.days.splice(i,1); t.selectedDayId=t.days[Math.max(0,i-1)]?.id||t.days[0].id; touchOrder(t); save("delete-day"); render(); }
function deleteList(id){ if(library.lists.length<=1) return toast("至少保留一个行程单"); const i=library.lists.findIndex(l=>l.id===id); const list=library.lists[i]; if(!list) return; markDeleted("lists",id); list.trip.days.forEach(d=>{ markDeleted("days",d.id); d.activities.forEach(a=>markDeleted("activities",a.id)); }); library.lists.splice(i,1); if(library.activeListId===id) library.activeListId=library.lists[Math.max(0,i-1)]?.id||library.lists[0].id; touch(library); save("delete-list"); render(); }
function bindDrag(el){ el.addEventListener("dragstart",e=>{ drag={type:el.classList.contains("day-card")?"day":"activity", id:el.dataset.dayId||el.dataset.activityId, el}; el.classList.add("dragging","live-drag-source"); e.dataTransfer.effectAllowed="move"; }); el.addEventListener("dragover",e=>{ if(!drag) return; e.preventDefault(); const target=e.currentTarget; if(target===drag.el) return; const before=e.clientY < target.getBoundingClientRect().top + target.offsetHeight/2; before?target.before(drag.el):target.after(drag.el); }); el.addEventListener("dragend",()=>{ commitDomOrder(); clearDrag(); }); el.addEventListener("drop",e=>{ e.preventDefault(); commitDomOrder(); clearDrag(); }); }
function commitDomOrder(){ if(!drag) return; const t=trip(); if(drag.type==="day"){ const ids=$$(".day-card",els.dayList).map(x=>x.dataset.dayId); t.days=ids.map(id=>t.days.find(d=>d.id===id)).filter(Boolean); t.selectedDayId=drag.id; touchOrder(t); save("reorder-days"); render(); return; } const rows=$$(".activity-row",els.dayList); const byDay=new Map(t.days.map(d=>[d.id,[]])); rows.forEach(row=>{ const dayId=row.closest(".day-card")?.dataset.dayId||row.dataset.dayId; const activity=t.days.flatMap(d=>d.activities).find(a=>a.id===row.dataset.activityId); if(dayId&&activity&&byDay.has(dayId)) byDay.get(dayId).push(activity); }); t.days.forEach(d=>{ if(byDay.has(d.id)){ d.activities=byDay.get(d.id); touchOrder(d); } }); save("reorder-activities"); render(); }
function clearDrag(){ drag=null; $$(".dragging,.live-drag-source").forEach(n=>n.classList.remove("dragging","live-drag-source")); }
function ensurePanels(){ ensureListToggle(); ensureSmartPanel(); }
function ensureListToggle(){ const head=$(".list-panel .section-heading"); if(!head||$(".list-collapse-toggle",head)) return; const b=document.createElement("button"); b.className="list-collapse-toggle"; b.type="button"; b.textContent="⌄"; b.onclick=()=>$(".list-panel")?.classList.toggle("is-collapsed"); head.append(b); }
function ensureSmartPanel(){ if($(".smart-panel")) return; const p=document.createElement("section"); p.className="smart-panel"; p.innerHTML=`<div class="smart-map-panel"><div class="smart-panel-head"><div><p class="eyeline">地图预览</p><h2 id="smartMapTitle">地图</h2></div><div class="segmented"><button type="button" data-map="day">当天</button><button type="button" data-map="list">当前list</button></div></div><div class="map-canvas" id="tripMap"></div><div class="map-status" id="mapStatus">点击计算路线</div></div><div class="ai-panel"><div class="smart-panel-head"><div><p class="eyeline">AI 推荐</p><h2 id="aiTitle">当天推荐</h2></div><button class="mini-action" id="aiBtn" type="button">推荐</button></div><div class="ai-status" id="aiStatus">选择天数或事项后生成推荐</div><div class="ai-results" id="aiResults"></div></div>`; els.dayList.before(p); $$('[data-map]',p).forEach(b=>b.onclick=()=>{ mapScope=b.dataset.map; renderSmart(); }); $("#aiBtn",p).onclick=loadAi; }
function renderSmart(){ const panel=$(".smart-panel"); if(!panel) return; const d=selectedDay(), i=trip().days.findIndex(x=>x.id===d?.id)+1; $("#smartMapTitle",panel).textContent=mapScope==="day"?`第 ${i} 天地图`:`${activeList().name} 全部地点`; $$('[data-map]',panel).forEach(b=>b.classList.toggle("active",b.dataset.map===mapScope)); renderAi(); }
async function loadAi(){ const s=$("#aiStatus"); s.textContent="正在生成推荐"; aiItems=[]; renderAi(); const d=selectedDay(); const target={...selectedContext}; if(target.activityId){ target.activity=d.activities.find(a=>a.id===target.activityId)||{}; } try{ const r=await fetch("/api/ai/recommend",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({trip:trip(),day:d,target})}); const j=await r.json(); if(!r.ok||!j.ok) throw new Error(j.error||"AI 推荐失败"); aiItems=j.recommendations||[]; s.textContent=aiItems.length?"推荐已生成":"暂无推荐"; renderAi(); }catch(e){ s.textContent=e.message.includes("key")?"Render 未配置 deepseek key":"AI 推荐失败，可重试"; } }
function renderAi(){ const box=$("#aiResults"); if(!box) return; box.replaceChildren(...aiItems.map((x)=>{ const c=document.createElement("article"); c.className="ai-card"; c.innerHTML=`<div><strong>${esc(x.title||x.name||"推荐事项")}</strong><span>${esc([x.time||x.suggestedTime,x.place||x.area].filter(Boolean).join(" · "))}</span>${x.note||x.reason?`<p>${esc(x.note||x.reason)}</p>`:""}</div><button class="mini-action" type="button">应用</button>`; $("button",c).onclick=()=>applyAiRecommendation(x); return c; })); }
function applyAiRecommendation(x){ const d=selectedDay(); if(selectedContext.activityId){ const a=d.activities.find(item=>item.id===selectedContext.activityId); if(a){ if(x.time&&!a.time) a.time=x.time; if((x.title||x.name)&&(!a.title||a.title==="未命名事项")) a.title=x.title||x.name; if((x.place||x.area)&&!a.place) a.place=x.place||x.area; if((x.note||x.reason)&&!a.note) a.note=x.note||x.reason; if(x.transport&&!a.transport) a.transport=normTransport(x.transport); if(x.budget) a.budget=x.budget; touch(a); touch(d); save("apply-ai-fill"); render(); return toast("已补全事项"); } } d.activities.push(normAct({time:x.time||"",title:x.title||x.name||"推荐事项",place:x.place||x.area||"",note:x.note||x.reason||"",transport:x.transport,budget:x.budget,updatedAt:now()})); touchOrder(d); save("add-ai"); render(); toast("已加入当天"); }
function save(reason){ if(applying) return; const l=activeList(), t=trip(); touch(t); l.trip=t; touch(l); library.updatedAt=now(); localStorage.setItem(storageKey,JSON.stringify(library)); setSync(wsReady?"正在保存到服务器":"本地待同步",wsReady); channel?.postMessage({type:"library",clientId,library,reason,revision}); send({type:"state",clientId,roomId,state:library,reason,baseRevision:revision}); scheduleSaveFallback(reason); }
function connect(){ if(location.protocol==="file:") return setSync("本地模式",false); ws=new WebSocket(`${location.protocol==="https:"?"wss":"ws"}://${location.host}/sync?room=${encodeURIComponent(roomId)}`); setSync("连接中",false); ws.onopen=()=>{ wsReady=true; setSync("已连接服务器",true); send({type:"join",clientId,roomId,name:localStorage.getItem(nameKey)||"我",state:library}); announce(); }; ws.onmessage=e=>{ const m=JSON.parse(e.data); if(m.type==="ack"){ clearSaveFallback(); revision=Math.max(revision,Number(m.revision)||0); if(m.state) applyRemote(m.state,"已保存到服务器",true,m.revision); return setSync("已保存到服务器",true); } if(m.clientId===clientId) return; if(m.revision) revision=Math.max(revision,Number(m.revision)||0); if(m.type==="state"&&m.state) applyRemote(m.state,m.clientId==="server"?"已同步":"协作者已更新",true,m.revision); if(m.type==="presence"){ membersOnline.set(m.clientId,{...m,at:now()}); } }; ws.onclose=()=>{ wsReady=false; setSync("离线保存",false); setTimeout(connect,1800); }; ws.onerror=()=>setSync("同步失败可重试",false); }
function scheduleSaveFallback(reason){ clearTimeout(saveFallbackTimer); saveFallbackTimer=setTimeout(()=>httpSave(reason), wsReady?2600:700); }
function clearSaveFallback(){ clearTimeout(saveFallbackTimer); saveFallbackTimer=0; }
async function fetchRoomState(){ try{ const r=await fetch(`/api/room-state?room=${encodeURIComponent(roomId)}`,{cache:"no-store"}); const j=await r.json(); if(!j.ok||!j.state) return; applyRemote(j.state,"已同步",true,Number(j.revision)||0); }catch{} }
async function httpSave(reason){ try{ const r=await fetch(`/api/room-state?room=${encodeURIComponent(roomId)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clientId,roomId,state:library,reason,baseRevision:revision})}); const j=await r.json(); if(!r.ok||!j.ok) throw new Error(j.error||"save failed"); revision=Math.max(revision,Number(j.revision)||0); if(j.state) applyRemote(j.state,"已保存到服务器",true,j.revision); setSync("已保存到服务器",true); }catch{ setSync("同步失败可重试",false); scheduleSaveFallback(reason); } }
function send(p){ if(wsReady&&ws?.readyState===WebSocket.OPEN) ws.send(JSON.stringify(p)); }
function applyRemote(data,msg,force=false,rev=revision){ const next=normLib(data?.lists?data:{lists:[makeList(data?.tripTitle||"共享行程",data)]}); applyLib(next,rev); setSync(msg||"已同步",true); }
function applyLib(next,rev=revision){ applying=true; revision=Math.max(revision,Number(rev)||0); library=normLib(next); localStorage.setItem(storageKey,JSON.stringify(library)); applying=false; render(); }
function announce(){ send({type:"presence",clientId,roomId,name:localStorage.getItem(nameKey)||"我"}); }
function exposeStore(){ window.TripPlanner={getLibrary:()=>clone(library),getRevision:()=>revision,getSelection:()=>({...selectedContext}),saveExternalLibrary(next,reason="external") { library=normLib(next); save(reason); render(); },selectDay(id){ selectDay(id); collapsedDays.delete(id); render(); },selectActivity(dayId,activityId,field=""){ selectActivity(dayId,activityId,field); render(); },openActivityEditor(dayId,activityId,field=""){ selectActivity(dayId,activityId,field); loadActivity(dayId,activityId,field==="transport"); }}; }
function selectDay(id){ if(trip().days.some(d=>d.id===id)){ trip().selectedDayId=id; mapScope="day"; selectedActivityId=""; selectedContext={type:"day",dayId:id,activityId:"",field:""}; } }
function selectActivity(dayId,activityId,field=""){ trip().selectedDayId=dayId; selectedActivityId=activityId; selectedContext={type:"activity",dayId,activityId,field}; }
function selectField(dayId,activityId,field){ selectActivity(dayId,activityId,field); }
function handleSelectionClick(event){ const row=event.target.closest?.(".activity-row[data-activity-id]"); if(row&&!event.target.closest(".activity-actions,.activity-drag-handle,.remove-activity")){ const field=event.target.closest("[data-select-field]")?.dataset.selectField||""; selectActivity(row.dataset.dayId,row.dataset.activityId,field); markSelectedDom(); } }
function markSelectedDom(){ $$(".selected-context").forEach(n=>n.classList.remove("selected-context")); if(selectedContext.activityId){ const row=$(`.activity-row[data-activity-id="${cssEscape(selectedContext.activityId)}"]`); row?.classList.add("selected-context"); if(selectedContext.field) row?.querySelector(`[data-select-field="${cssEscape(selectedContext.field)}"]`)?.classList.add("selected-context"); } else if(selectedContext.dayId){ $(`.day-card[data-day-id="${cssEscape(selectedContext.dayId)}"]`)?.classList.add("selected-context"); } }
function copyLink(){ const u=new URL(location.href); u.searchParams.set("room",roomId); navigator.clipboard?.writeText(u).then(()=>toast("协作链接已复制"),()=>toast(u.toString())); }
function ensureRoom(){ if(params.get("room")) return; const u=new URL(location.href); u.searchParams.set("room",roomId); history.replaceState(null,"",u); }
function transportLabel(t){ if(!t) return ""; const label=transportTypes.find(([id])=>id===t.type)?.[1]||"交通"; return [label,[t.from,t.to].filter(Boolean).join(" → "),[t.depart,t.arrive].filter(Boolean).join("-")].filter(Boolean).join(" · "); }
function pill(text){ const s=document.createElement("span"); s.className="meta-pill"; s.textContent=text; return s; }
function setSync(text,on){ els.syncText.textContent=text; els.syncState.classList.toggle("connected",!!on); els.syncState.classList.toggle("offline",!on); }
function toast(text){ els.toast.textContent=text; els.toast.classList.add("show"); setTimeout(()=>els.toast.classList.remove("show"),1800); }
function esc(v){ return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])); }
function cssEscape(value){ if(window.CSS?.escape) return CSS.escape(value); return String(value||"").replace(/"/g,'\\"'); }
function clone(v){ return JSON.parse(JSON.stringify(v)); }
