const transportTypes = [
  ["plane", "飞机"], ["train", "火车"], ["bus", "大巴"], ["boat", "船"], ["car", "车"]
];
const params = new URLSearchParams(location.search);
const roomId = params.get("room") || Array.from(crypto.getRandomValues(new Uint8Array(4))).map((v)=>v.toString(16).padStart(2,"0")).join("").toUpperCase();
const storageKey = `trip-planner-library:${roomId}`;
const legacyStorageKey = `trip-planner:${roomId}`;
const clientKey = "trip-planner:client-id";
const nameKey = "trip-planner:member-name";
const clientId = localStorage.getItem(clientKey) || crypto.randomUUID();
localStorage.setItem(clientKey, clientId);
const channel = "BroadcastChannel" in window ? new BroadcastChannel(storageKey) : null;
const hadLocal = hasStoredLocalData();
let library = loadLibrary();
let ws, wsReady = false, revision = 0, localWrites = 0, applying = false;
let saveFallbackTimer = 0;
let membersOnline = new Map();
let selectedActivityId = "";
const collapsedDays = new Set();
let drag = null;
let mapScope = "list", map, markerLayer;
let geocodeCache = new Map();
let aiItems = [];
const $ = (s, r = document) => r.querySelector(s);
const $$ = (s, r = document) => [...r.querySelectorAll(s)];
const els = {
  title: $("#tripTitle"), start: $("#startDate"), origin: $("#originCity"), member: $("#memberName"), members: $("#memberStrip"),
  room: $("#roomCode"), lists: $("#tripList"), addList: $("#addListBtn"), listName: $("#listNameInput"), dayLimit: $("#dayLimitInput"), dayLimitValue: $("#dayLimitValue"),
  dayCount: $("#dayCount"), activityCount: $("#activityCount"), stayCount: $("#stayCount"), transportSummary: $("#transportSummary"), dayList: $("#dayList"),
  addDay: $("#addDayBtn"), addDayTop: $("#addDayTopBtn"), syncState: $("#syncState"), syncText: $("#syncText"), copy: $("#copyLinkBtn"), detailLabel: $("#detailLabel"),
  delDay: $("#deleteDayBtn"), loc: $("#detailLocation"), stay: $("#detailStay"), tabs: $("#transportTabs"), from: $("#transportFrom"), to: $("#transportTo"),
  depart: $("#transportDepart"), arrive: $("#transportArrive"), form: $("#activityForm"), formLabel: $("#activityFormLabel"), submitText: $("#activitySubmitText"),
  cancel: $("#cancelEditActivityBtn"), clearTransport: $("#clearTransportBtn"), time: $("#activityTime"), place: $("#activityPlace"), activityTitle: $("#activityTitle"), note: $("#activityNote"), toast: $("#toast")
};
init();
function init(){ ensureRoom(); if(!localStorage.getItem(nameKey)) localStorage.setItem(nameKey,"我"); exposeStore(); bind(); render(); connect(); fetchRoomState(); }
function today(){ const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000); return d.toISOString().slice(0,10); }
function blankTrip(name="新行程单"){ const day={id:crypto.randomUUID(),location:"",stay:"",activities:[]}; return {version:1,tripTitle:name,startDate:today(),originCity:"",selectedDayId:day.id,dayLimit:30,updatedAt:Date.now(),days:[day]}; }
function makeList(name="新行程单", trip=blankTrip(name)){ trip.tripTitle ||= name; trip.selectedDayId ||= trip.days?.[0]?.id || ""; return {id:crypto.randomUUID(),name,trip,createdAt:Date.now(),updatedAt:Date.now()}; }
function loadLibrary(){
  try{ const v=JSON.parse(localStorage.getItem(storageKey)); if(v?.lists?.length) return normLib(v); }catch{ localStorage.removeItem(storageKey); }
  try{ const v=JSON.parse(localStorage.getItem(legacyStorageKey)); if(v?.days?.length) return normLib({version:2,activeListId:"",lists:[makeList(v.tripTitle||"我的行程单",v)],updatedAt:Date.now()}); }catch{}
  const l=makeList("新行程单"); return normLib({version:2,activeListId:l.id,members:[],lists:[l],updatedAt:Date.now()});
}
function normLib(input={}){ const lists=(input.lists||[]).filter(x=>x?.trip?.days?.length).map((l,i)=>{ l={...l}; l.id ||= crypto.randomUUID(); l.trip=normTrip(l.trip); l.name=(l.name||l.trip.tripTitle||`行程单 ${i+1}`).trim(); l.trip.tripTitle ||= l.name; l.updatedAt ||= l.trip.updatedAt||Date.now(); l.createdAt ||= Date.now(); return l; }); if(!lists.length) lists.push(makeList()); return {version:2,activeListId:lists.some(l=>l.id===input.activeListId)?input.activeListId:lists[0].id,members:normMembers(input.members),lists,updatedAt:input.updatedAt||Date.now()}; }
function normMembers(ms=[]){ const seen=new Set(); return (Array.isArray(ms)?ms:[]).map(m=>({id:m?.id||crypto.randomUUID(),name:String(m?.name||"").trim(),createdAt:m?.createdAt||Date.now(),updatedAt:m?.updatedAt||Date.now()})).filter(m=>m.name&&!seen.has(m.id)&&seen.add(m.id)); }
function normTrip(t={}){ const days=(t.days||[]).map(normDay).filter(Boolean); return {...t,tripTitle:t.tripTitle||"新行程单",startDate:t.startDate||today(),originCity:t.originCity||"",selectedDayId:t.selectedDayId||days[0]?.id||"",dayLimit:Math.max(days.length||1,Math.min(60,Number(t.dayLimit)||30)),updatedAt:t.updatedAt||Date.now(),days:days.length?days:blankTrip(t.tripTitle).days}; }
function normDay(d={}){ return {id:d.id||crypto.randomUUID(),location:d.location||"",stay:d.stay||"",activities:(d.activities||[]).map(normAct)}; }
function normAct(a={}){ return {id:a.id||crypto.randomUUID(),time:a.time||"",title:a.title||"未命名事项",place:a.place||"",note:a.note||"",done:Boolean(a.done),budget:a.budget||null,transport:normTransport(a.transport)}; }
function normTransport(t){ if(!t||typeof t!=="object") return null; const n={type:t.type||"",from:t.from||"",to:t.to||"",depart:t.depart||"",arrive:t.arrive||""}; if(!Object.values(n).some(Boolean)) return null; if(!transportTypes.some(([id])=>id===n.type)) n.type="train"; return n; }
function activeList(){ return library.lists.find(l=>l.id===library.activeListId)||library.lists[0]; }
function trip(){ return activeList().trip; }
function selectedDay(){ return trip().days.find(d=>d.id===trip().selectedDayId)||trip().days[0]; }
function dayDate(i){ const d=new Date(`${trip().startDate}T00:00:00`); d.setDate(d.getDate()+i); return d; }
function bind(){
  els.title.oninput=()=>updateTrip({tripTitle:els.title.value}); els.start.onchange=()=>updateTrip({startDate:els.start.value}); els.origin.oninput=()=>updateTrip({originCity:els.origin.value});
  els.dayLimit.oninput=()=>{ trip().dayLimit=Math.max(trip().days.length,Number(els.dayLimit.value)||30); save("day-limit"); render(); };
  els.addList.onclick=()=>{ const l=makeList(`新行程单 ${library.lists.length+1}`); library.lists.push(l); library.activeListId=l.id; save("add-list"); render(); els.listName.focus(); };
  els.listName.oninput=()=>{ activeList().name=els.listName.value.trim()||"未命名行程单"; trip().tripTitle=activeList().name; save("rename-list"); renderLists(); };
  els.member.oninput=()=>{ localStorage.setItem(nameKey,els.member.value.trim()||"我"); announce(); };
  els.addDay.onclick=els.addDayTop.onclick=addDay; els.delDay.onclick=()=>deleteDay(selectedDay()?.id); els.copy.onclick=copyLink;
  els.loc.oninput=()=>{ selectedDay().location=els.loc.value; save("day-location"); renderLight(); };
  els.stay.oninput=()=>{ selectedDay().stay=els.stay.value; save("day-stay"); renderLight(); };
  els.clearTransport.onclick=()=>{ els.tabs.dataset.type=""; els.from.value=els.to.value=els.depart.value=els.arrive.value=""; renderTabs(); };
  els.cancel.onclick=()=>resetForm(); els.form.onsubmit=saveActivity;
  channel?.addEventListener("message",e=>{
    if(e.data?.type!=="library"||e.data.clientId===clientId) return;
    applyRemote(e.data.library,"同浏览器标签页已同步",false);
    const externalId=String(e.data.clientId||"");
    if(externalId.startsWith("quick-plan:")||externalId.startsWith("trip-insights:")) save(e.data.reason||"external-widget");
  });
  window.addEventListener("beforeunload",()=>send({type:"leave",clientId}));
}
function render(){ const t=trip(), l=activeList(); els.title.value=t.tripTitle; els.start.value=t.startDate; els.origin.value=t.originCity||""; els.member.value=localStorage.getItem(nameKey)||"我"; els.listName.value=l.name; els.room.textContent=roomId; els.dayLimit.value=t.dayLimit; els.dayLimitValue.textContent=`${t.dayLimit} 天`; renderTabs(); ensurePanels(); renderLists(); renderStats(); renderMembers(); renderDays(); renderDetail(); renderSmart(); }
function renderLight(){ renderStats(); renderDays(); renderDetail(); renderSmart(); }
function renderLists(){ els.lists.replaceChildren(...library.lists.map(l=>{ const row=document.createElement("div"); row.className=`trip-list-row ${l.id===library.activeListId?"active":""}`; const count=l.trip.days.reduce((s,d)=>s+d.activities.length,0); row.innerHTML=`<button class="trip-list-item ${l.id===library.activeListId?"active":""}" type="button"><span class="trip-list-name">${esc(l.name)}</span><span class="trip-list-meta">${l.trip.days.length} 天 · ${count} 项</span></button><button class="trip-list-delete" type="button" title="删除行程单" ${library.lists.length<=1?"disabled":""}>×</button>`; $(".trip-list-item",row).onclick=()=>{ library.activeListId=l.id; mapScope="list"; render(); }; $(".trip-list-delete",row).onclick=()=>deleteList(l.id); return row; })); }
function renderStats(){ const t=trip(), acts=t.days.flatMap(d=>d.activities); els.dayCount.textContent=`${t.days.length} / ${t.dayLimit} 天`; els.activityCount.textContent=acts.length; els.stayCount.textContent=t.days.filter(d=>d.stay.trim()).length; els.transportSummary.replaceChildren(...transportTypes.map(([id,label])=>[label,acts.filter(a=>a.transport?.type===id).length]).filter(([,n])=>n).map(([label,n])=>pill(`${label} ${n}`))); }
function renderMembers(){ membersOnline.set(clientId,{clientId,name:localStorage.getItem(nameKey)||"我",at:Date.now()}); const wrap=document.createDocumentFragment(); const managed=document.createElement("div"); managed.className="managed-members"; (library.members||[]).forEach(m=>{ const node=document.createElement("label"); node.className="managed-member"; node.innerHTML=`<span class="avatar">${esc(m.name[0]||"?")}</span><input value="${esc(m.name)}" aria-label="修改同行人"><button class="member-delete" type="button">×</button>`; $("input",node).onchange=e=>{ m.name=e.target.value.trim()||"未命名"; m.updatedAt=Date.now(); save("rename-member"); renderMembers(); }; $("button",node).onclick=()=>{ library.members=library.members.filter(x=>x.id!==m.id); save("delete-member"); renderMembers(); }; managed.append(node); }); const add=document.createElement("button"); add.className="mini-action member-add-action"; add.type="button"; add.textContent="添加同行人"; add.onclick=()=>{ library.members=normMembers([...(library.members||[]),{name:els.member.value||"新同行人"}]); save("add-member"); renderMembers(); }; managed.append(add); wrap.append(managed); const online=document.createElement("div"); online.className="online-members"; [...membersOnline.values()].filter(m=>Date.now()-m.at<25000).forEach(m=>{ const b=document.createElement("button"); b.className="member online-member"; b.type="button"; b.innerHTML=`<span class="avatar">${esc((m.name||"?")[0])}</span>${esc(m.name||"同行者")}`; if(m.clientId===clientId) b.onclick=()=>els.member.focus(); online.append(b); }); wrap.append(online); els.members.replaceChildren(wrap); }
function renderDays(){ const t=trip(); const visibleIds=new Set(t.days.map(d=>d.id)); [...collapsedDays].forEach(id=>{ if(!visibleIds.has(id)) collapsedDays.delete(id); }); els.addDay.disabled=els.addDayTop.disabled=t.days.length>=t.dayLimit; els.dayList.replaceChildren(...t.days.map((d,i)=>{ const isCollapsed=collapsedDays.has(d.id); const budget=dayBudgetText(d); const card=document.createElement("article"); card.className=`day-card day-card-compact ${d.id===t.selectedDayId?"active":""} ${isCollapsed?"is-collapsed":"is-expanded"}`; card.dataset.dayId=d.id; card.draggable=true; card.innerHTML=`<button class="day-main" type="button" aria-expanded="${!isCollapsed}"><span class="day-index">第 ${i+1} 天</span><span class="day-date">${new Intl.DateTimeFormat("zh-CN",{month:"long",day:"numeric"}).format(dayDate(i))}</span><span class="day-weekday">${new Intl.DateTimeFormat("zh-CN",{weekday:"long"}).format(dayDate(i))}</span><span class="day-compact-location">城市 ${esc(d.location||"未填写地点")}</span><span class="day-compact-stay">住宿 ${esc(d.stay||"未填写")}</span><span class="day-compact-budget">${esc(budget)}</span><span class="day-compact-count">${d.activities.length} 项</span><span class="day-inline-actions"><button class="day-delete-inline" type="button" ${t.days.length<=1?"disabled":""}>×</button><span class="drag-handle day-drag-handle" draggable="true">⋮⋮</span></span></button><div class="day-content"><div class="day-meta"></div><div class="activity-list" data-day-id="${d.id}"></div></div>`; $(".day-main",card).onclick=e=>{ if(e.target.closest(".day-delete-inline,.drag-handle")) return; if(t.selectedDayId===d.id){ if(collapsedDays.has(d.id)) collapsedDays.delete(d.id); else collapsedDays.add(d.id); } else { collapsedDays.delete(d.id); } t.selectedDayId=d.id; mapScope="day"; selectedActivityId=""; render(); }; $(".day-delete-inline",card).onclick=e=>{ e.stopPropagation(); deleteDay(d.id); }; const meta=$(".day-meta",card); meta.append(pill(`城市 ${d.location||"未填写地点"}`), pill(`住宿 ${d.stay||"未填写"}`), pill(budget)); const list=$(".activity-list",card); if(!d.activities.length){ const empty=document.createElement("div"); empty.className="empty-state"; empty.textContent="还没有事项"; list.append(empty); } else d.activities.forEach(a=>list.append(activityRow(d.id,a))); bindDrag(card); return card; })); }
function dayBudgetText(day){ const info=dayBudgetInfo(day); return info.total?`预算 ${formatBudget(info.total,info.currency)}`:"预算未估算"; }
function dayBudgetInfo(day){ const t=trip(), items=t.budget?.items||{}, fallbackCurrency=t.budget?.currency||day.activities.find(a=>a.budget?.currency)?.budget.currency||"CNY"; const total=(day.activities||[]).reduce((sum,a)=>{ const item=items[a.id]; if(item&&Number.isFinite(Number(item.cost))) return sum+Number(item.cost); const own=a.budget||{}; const value=Number(own.amount??own.cost??0); return Number.isFinite(value)?sum+value:sum; },0); return {total,currency:fallbackCurrency}; }
function formatBudget(value,currency="CNY"){ const digits=currency==="CNY"||currency==="JPY"?0:2; try{ return new Intl.NumberFormat("zh-CN",{style:"currency",currency,minimumFractionDigits:digits,maximumFractionDigits:digits}).format(value); }catch{ return `${currency} ${Math.round(value).toLocaleString("zh-CN")}`; } }
function activityRow(dayId,a){ const row=document.createElement("div"); row.className=`activity-row ${a.id===selectedActivityId?"editing":""}`; row.dataset.dayId=dayId; row.dataset.activityId=a.id; row.draggable=true; const tr=transportLabel(a.transport); row.innerHTML=`<span class="activity-time">${esc(a.time||"")}</span><span class="activity-body"><strong>${esc(a.title)}</strong>${a.place?`<span>${esc(a.place)}</span>`:""}${a.note?`<p>${esc(a.note)}</p>`:""}${tr?`<button class="activity-transport-chip" type="button">${esc(tr)}</button>`:`<button class="activity-transport-add" type="button">添加交通</button>`}</span><span class="activity-actions"><button class="activity-drag-handle" type="button">⋮⋮</button><button class="edit-activity" type="button">✎</button><button class="remove-activity" type="button">×</button></span>`; $(".edit-activity",row).onclick=()=>loadActivity(dayId,a.id); $(".activity-transport-chip,.activity-transport-add",row).onclick=()=>loadActivity(dayId,a.id,true); $(".remove-activity",row).onclick=()=>{ const d=trip().days.find(x=>x.id===dayId); d.activities=d.activities.filter(x=>x.id!==a.id); save("delete-activity"); render(); }; bindDrag(row); return row; }
function renderDetail(){ const t=trip(), d=selectedDay(), i=t.days.findIndex(x=>x.id===d?.id); if(!d) return; els.detailLabel.textContent=`第 ${i+1} 天`; els.delDay.disabled=t.days.length<=1; if(document.activeElement!==els.loc) els.loc.value=d.location; if(document.activeElement!==els.stay) els.stay.value=d.stay; }
function renderTabs(){ const type=els.tabs.dataset.type||""; els.tabs.replaceChildren(...transportTypes.map(([id,label])=>{ const b=document.createElement("button"); b.className=`transport-tab ${type===id?"active":""}`; b.type="button"; b.textContent=label; b.onclick=()=>{ els.tabs.dataset.type=id; renderTabs(); }; return b; })); }
function saveActivity(e){ e.preventDefault(); const d=selectedDay(); const payload=normAct({id:selectedActivityId||crypto.randomUUID(),time:els.time.value,title:els.activityTitle.value.trim(),place:els.place.value.trim(),note:els.note.value.trim(),transport:{type:els.tabs.dataset.type,from:els.from.value.trim(),to:els.to.value.trim(),depart:els.depart.value,arrive:els.arrive.value}}); if(selectedActivityId){ const old=d.activities.find(a=>a.id===selectedActivityId); if(old) Object.assign(old,payload); } else d.activities.push(payload); selectedActivityId=""; resetForm(); save("save-activity"); render(); toast("事项已保存"); }
function loadActivity(dayId,id,focusTransport=false){ const t=trip(), d=t.days.find(x=>x.id===dayId), a=d?.activities.find(x=>x.id===id); if(!a) return; t.selectedDayId=dayId; selectedActivityId=id; els.time.value=a.time||""; els.place.value=a.place||""; els.activityTitle.value=a.title||""; els.note.value=a.note||""; els.tabs.dataset.type=a.transport?.type||""; els.from.value=a.transport?.from||""; els.to.value=a.transport?.to||""; els.depart.value=a.transport?.depart||""; els.arrive.value=a.transport?.arrive||""; renderTabs(); render(); requestAnimationFrame(()=> (focusTransport?els.from:els.activityTitle).focus()); }
function resetForm(){ selectedActivityId=""; els.form.reset(); els.tabs.dataset.type=""; renderTabs(); }
function updateTrip(p){ Object.assign(trip(),p); if(p.tripTitle!==undefined){ activeList().name=p.tripTitle.trim()||"未命名行程单"; } save("update-trip"); renderLight(); renderLists(); }
function addDay(){ const t=trip(); if(t.days.length>=t.dayLimit) return toast("已达到天数上限"); const d={id:crypto.randomUUID(),location:"",stay:"",activities:[]}; t.days.push(d); t.selectedDayId=d.id; save("add-day"); render(); }
function deleteDay(id){ const t=trip(); if(t.days.length<=1) return toast("至少保留一天"); const i=t.days.findIndex(d=>d.id===id); if(i<0) return; collapsedDays.delete(id); t.days.splice(i,1); t.selectedDayId=t.days[Math.max(0,i-1)]?.id||t.days[0].id; save("delete-day"); render(); }
function deleteList(id){ if(library.lists.length<=1) return toast("至少保留一个行程单"); const i=library.lists.findIndex(l=>l.id===id); library.lists.splice(i,1); if(library.activeListId===id) library.activeListId=library.lists[Math.max(0,i-1)]?.id||library.lists[0].id; save("delete-list"); render(); }
function bindDrag(el){ el.addEventListener("dragstart",e=>{ drag={type:el.classList.contains("day-card")?"day":"activity", id:el.dataset.dayId||el.dataset.activityId, el}; el.classList.add("dragging","live-drag-source"); e.dataTransfer.effectAllowed="move"; }); el.addEventListener("dragover",e=>{ if(!drag) return; e.preventDefault(); const target=e.currentTarget; if(target===drag.el) return; const before=e.clientY < target.getBoundingClientRect().top + target.offsetHeight/2; before?target.before(drag.el):target.after(drag.el); }); el.addEventListener("dragend",()=>{ commitDomOrder(); clearDrag(); }); el.addEventListener("drop",e=>{ e.preventDefault(); commitDomOrder(); clearDrag(); }); }
function commitDomOrder(){ if(!drag) return; const t=trip(); if(drag.type==="day"){ const ids=$$(".day-card",els.dayList).map(x=>x.dataset.dayId); t.days=ids.map(id=>t.days.find(d=>d.id===id)).filter(Boolean); t.selectedDayId=drag.id; save("reorder-days"); render(); return; } const rows=$$(".activity-row",els.dayList); const byDay=new Map(t.days.map(d=>[d.id,[]])); rows.forEach(row=>{ const dayId=row.closest(".day-card")?.dataset.dayId||row.dataset.dayId; const activity=t.days.flatMap(d=>d.activities).find(a=>a.id===row.dataset.activityId); if(dayId&&activity&&byDay.has(dayId)) byDay.get(dayId).push(activity); }); t.days.forEach(d=>{ if(byDay.has(d.id)) d.activities=byDay.get(d.id); }); save("reorder-activities"); render(); }
function clearDrag(){ drag=null; $$(".dragging,.live-drag-source").forEach(n=>n.classList.remove("dragging","live-drag-source")); }
function ensurePanels(){ ensureListToggle(); ensureSmartPanel(); }
function ensureListToggle(){ const head=$(".list-panel .section-heading"); if(!head||$(".list-collapse-toggle",head)) return; const b=document.createElement("button"); b.className="list-collapse-toggle"; b.type="button"; b.textContent="⌄"; b.onclick=()=>$(".list-panel")?.classList.toggle("is-collapsed"); head.append(b); }
function ensureSmartPanel(){ if($(".smart-panel")) return; const p=document.createElement("section"); p.className="smart-panel"; p.innerHTML=`<div class="smart-map-panel"><div class="smart-panel-head"><div><p class="eyeline">地图预览</p><h2 id="smartMapTitle">地图</h2></div><div class="segmented"><button type="button" data-map="day">当天</button><button type="button" data-map="list">全 list</button></div></div><div class="map-canvas" id="tripMap"></div><div class="map-status" id="mapStatus"></div></div><div class="ai-panel"><div class="smart-panel-head"><div><p class="eyeline">AI 推荐</p><h2 id="aiTitle">当天推荐</h2></div><button class="mini-action" id="aiBtn" type="button">推荐当天</button></div><div class="ai-status" id="aiStatus">点击生成推荐</div><div class="ai-results" id="aiResults"></div></div>`; els.dayList.before(p); $$('[data-map]',p).forEach(b=>b.onclick=()=>{ mapScope=b.dataset.map; renderSmart(); }); $("#aiBtn",p).onclick=loadAi; }
function renderSmart(){ const panel=$(".smart-panel"); if(!panel) return; const d=selectedDay(), i=trip().days.findIndex(x=>x.id===d?.id)+1; $("#smartMapTitle",panel).textContent=mapScope==="day"?`第 ${i} 天地图`:`${activeList().name} 全部地点`; $$('[data-map]',panel).forEach(b=>b.classList.toggle("active",b.dataset.map===mapScope)); renderAi(); renderMap(); }
async function renderMap(){ const status=$("#mapStatus"), canvas=$("#tripMap"); if(!window.L){ status.textContent="地图组件加载中"; return; } if(!map){ map=L.map(canvas,{scrollWheelZoom:false}); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap"}).addTo(map); markerLayer=L.layerGroup().addTo(map); } requestAnimationFrame(()=>map.invalidateSize()); markerLayer.clearLayers(); const entries=mapEntries(); if(!entries.length){ status.textContent="还没有可定位地点"; map.setView([35,105],4); return; } const located=[]; for(const e of entries){ const g=await geocode(e.query); if(g) located.push({...e,...g}); } if(!located.length){ status.textContent="未定位，请填写更具体地点"; return; } const bounds=[]; located.forEach(e=>{ L.marker([e.lat,e.lon]).bindPopup(`<b>${esc(e.label)}</b><br>${esc(e.day)}`).addTo(markerLayer); bounds.push([e.lat,e.lon]); }); map.fitBounds(bounds,{padding:[24,24],maxZoom:15}); status.textContent=`已定位 ${located.length} 个地点`; }
function mapEntries(){ const days=mapScope==="day"?[selectedDay()]:trip().days, out=[], seen=new Set(); days.filter(Boolean).forEach((d,i)=>{ const idx=trip().days.indexOf(d)+1; addEntry(out,seen,d.location,d.location,`第 ${idx} 天`); addEntry(out,seen,[d.location,d.stay].filter(Boolean).join(" "),d.stay,`第 ${idx} 天住宿`); d.activities.forEach(a=>addEntry(out,seen,[d.location,a.place||a.title].filter(Boolean).join(" "),a.place||a.title,`第 ${idx} 天 · ${a.title}`)); }); return out.slice(0,35); }
function addEntry(out,seen,query,label,day){ query=String(query||"").trim(); label=String(label||"").trim(); if(!query||!label||seen.has(day+query)) return; seen.add(day+query); out.push({query,label,day}); }
async function geocode(q){ if(geocodeCache.has(q)) return geocodeCache.get(q); try{ const r=await fetch(`/api/geocode?q=${encodeURIComponent(q)}`); const j=await r.json(); const p=j.results?.[0]||j.result; const g=p?{lat:Number(p.lat),lon:Number(p.lon??p.lng)}:null; geocodeCache.set(q,g); return g; }catch{ geocodeCache.set(q,null); return null; } }
async function loadAi(){ const s=$("#aiStatus"); s.textContent="正在生成推荐"; aiItems=[]; renderAi(); try{ const r=await fetch("/api/ai/recommend",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({trip:trip(),day:selectedDay()})}); const j=await r.json(); if(!r.ok||!j.ok) throw new Error(j.error||"AI 推荐失败"); aiItems=j.recommendations||[]; s.textContent=aiItems.length?"推荐已生成":"暂无推荐"; renderAi(); }catch(e){ s.textContent=e.message.includes("key")?"Render 未配置 deepseek key":"AI 推荐失败，可重试"; } }
function renderAi(){ const box=$("#aiResults"); if(!box) return; box.replaceChildren(...aiItems.map((x,i)=>{ const c=document.createElement("article"); c.className="ai-card"; c.innerHTML=`<div><strong>${esc(x.title||x.name||"推荐事项")}</strong><span>${esc([x.time||x.suggestedTime,x.place||x.area].filter(Boolean).join(" · "))}</span>${x.note||x.reason?`<p>${esc(x.note||x.reason)}</p>`:""}</div><button class="mini-action" type="button">加入当天</button>`; $("button",c).onclick=()=>{ selectedDay().activities.push(normAct({time:x.time||"",title:x.title||x.name||"推荐事项",place:x.place||x.area||"",note:x.note||x.reason||"",transport:x.transport,budget:x.budget})); save("add-ai"); render(); }; return c; })); }
function save(reason){ if(applying) return; const l=activeList(), t=trip(); t.updatedAt=Date.now(); l.trip=t; l.updatedAt=t.updatedAt; library.updatedAt=Date.now(); localStorage.setItem(storageKey,JSON.stringify(library)); localWrites++; setSync(wsReady?"正在保存到服务器":"本地待同步",wsReady); channel?.postMessage({type:"library",clientId,library,reason}); send({type:"state",clientId,roomId,state:library,reason,baseRevision:revision}); scheduleSaveFallback(reason); }
function connect(){ if(location.protocol==="file:") return setSync("本地模式",false); ws=new WebSocket(`${location.protocol==="https:"?"wss":"ws"}://${location.host}/sync?room=${encodeURIComponent(roomId)}`); setSync("连接中",false); ws.onopen=()=>{ wsReady=true; setSync("已连接服务器",true); send({type:"join",clientId,roomId,name:localStorage.getItem(nameKey)||"我",state:library}); announce(); }; ws.onmessage=e=>{ const m=JSON.parse(e.data); if(m.type==="ack"){ clearSaveFallback(); revision=Math.max(revision,Number(m.revision)||0); return setSync("已保存到服务器",true); } if(m.type==="conflict"){ clearSaveFallback(); return handleConflict(m.state,Number(m.revision)||0); } if(m.clientId===clientId) return; if(m.revision) revision=Math.max(revision,Number(m.revision)||0); if(m.type==="state"&&m.state) applyRemote(m.state,m.clientId==="server"?"已同步":"协作者已更新",m.clientId==="server",m.revision); if(m.type==="presence"){ membersOnline.set(m.clientId,{...m,at:Date.now()}); renderMembers(); } if(m.type==="members"){ membersOnline=new Map((m.members||[]).map(x=>[x.clientId,{...x,at:Date.now()}])); renderMembers(); } }; ws.onclose=()=>{ wsReady=false; setSync("离线保存",false); setTimeout(connect,1800); }; ws.onerror=()=>setSync("同步失败可重试",false); }
function scheduleSaveFallback(reason){ clearTimeout(saveFallbackTimer); saveFallbackTimer=setTimeout(()=>httpSave(reason), wsReady?2600:700); }
function clearSaveFallback(){ clearTimeout(saveFallbackTimer); saveFallbackTimer=0; }
async function fetchRoomState(){ try{ const r=await fetch(`/api/room-state?room=${encodeURIComponent(roomId)}`,{cache:"no-store"}); const j=await r.json(); if(!j.ok||!j.state) return; applyRemote(j.state,"已同步",true,Number(j.revision)||0); }catch{} }
async function httpSave(reason){ try{ const r=await fetch(`/api/room-state?room=${encodeURIComponent(roomId)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clientId,roomId,state:library,reason,baseRevision:revision})}); const j=await r.json(); if(r.status===409&&j.state){ handleConflict(j.state,Number(j.revision)||0); return; } if(!r.ok||!j.ok) throw new Error(j.error||"save failed"); revision=Math.max(revision,Number(j.revision)||0); setSync("已保存到服务器",true); }catch{ setSync("同步失败可重试",false); scheduleSaveFallback(reason); } }
function send(p){ if(wsReady&&ws?.readyState===WebSocket.OPEN) ws.send(JSON.stringify(p)); }
function applyRemote(data,msg,force=false,rev=revision){ const next=normLib(data?.lists?data:{lists:[makeList(data?.tripTitle||"共享行程",data)]}); if(force&&(hadLocal||localWrites)&&hash(next)!==hash(library)){ const merged=backup(next,library); if(merged.lists.length>next.lists.length){ applyLib(merged,rev); setSync("冲突已备份",true); save("conflict-backup"); return toast("本地差异已保存成冲突备份 list"); } } if(!force&&next.updatedAt<library.updatedAt) return; applyLib(next,rev); setSync(msg==="已同步"?"已同步":"已同步",true); }
function applyLib(next,rev=revision){ applying=true; revision=Math.max(revision,Number(rev)||0); library=normLib(next); localStorage.setItem(storageKey,JSON.stringify(library)); applying=false; render(); }
function handleConflict(server,rev){ const merged=backup(normLib(server),library); applyLib(merged,rev); if(merged.lists.length>normLib(server).lists.length){ setSync("冲突已备份",true); save("conflict-backup"); } else setSync("已载入服务器版本",true); }
function backup(server,local){ const merged=clone(server), hashes=new Set(merged.lists.map(l=>hash(l.trip))), time=new Date().toLocaleString("zh-CN",{hour12:false}); const serverUpdated=Number(merged.updatedAt||Math.max(...merged.lists.map(l=>Number(l.updatedAt||l.trip?.updatedAt||0)),0)); let activated=false; (local.lists||[]).forEach(l=>{ if(!isMeaningfulList(l)) return; const h=hash(l.trip); if(hashes.has(h)) return; const b=clone(l); b.id=crypto.randomUUID(); b.name=`冲突备份 - ${l.name||"本地行程"} - ${time}`; b.updatedAt=Date.now(); merged.lists.push(b); hashes.add(h); const localUpdated=Number(local.updatedAt||l.updatedAt||l.trip?.updatedAt||0); if(!activated&&localUpdated>=serverUpdated){ merged.activeListId=b.id; activated=true; } }); merged.updatedAt=Date.now(); return normLib(merged); }
function announce(){ send({type:"presence",clientId,roomId,name:localStorage.getItem(nameKey)||"我"}); }
function exposeStore(){ window.TripPlanner={getLibrary:()=>clone(library),getRevision:()=>revision,saveExternalLibrary(next,reason="external") { library=normLib(next); save(reason); render(); },selectDay(id){ if(trip().days.some(d=>d.id===id)){ collapsedDays.delete(id); trip().selectedDayId=id; mapScope="day"; render(); }}}; }
function hasStoredLocalData(){ return [storageKey,legacyStorageKey].some(key=>{ try{ const raw=localStorage.getItem(key); if(!raw) return false; const data=JSON.parse(raw); if(data?.lists?.some(isMeaningfulList)) return true; if(data?.days?.length) return isMeaningfulTrip(data); return false; }catch{ return false; } }); }
function isMeaningfulList(list){ if(!list?.trip) return false; const name=String(list.name||list.trip.tripTitle||"").trim(); return isMeaningfulTrip(list.trip)||Boolean(name&&name!=="新行程单"&&name!=="未命名行程单"); }
function isMeaningfulTrip(t){ if(!t) return false; const title=String(t.tripTitle||"").trim(); if(title&&title!=="新行程单"&&title!=="未命名行程单") return true; if(String(t.originCity||"").trim()) return true; const days=Array.isArray(t.days)?t.days:[]; if(days.length>1) return true; return days.some(d=>String(d.location||"").trim()||String(d.stay||"").trim()||(d.activities||[]).length); }
function copyLink(){ const u=new URL(location.href); u.searchParams.set("room",roomId); navigator.clipboard?.writeText(u).then(()=>toast("协作链接已复制"),()=>toast(u.toString())); }
function ensureRoom(){ if(params.get("room")) return; const u=new URL(location.href); u.searchParams.set("room",roomId); history.replaceState(null,"",u); }
function transportLabel(t){ if(!t) return ""; const label=transportTypes.find(([id])=>id===t.type)?.[1]||"交通"; return [label,[t.from,t.to].filter(Boolean).join(" → "),[t.depart,t.arrive].filter(Boolean).join("-")].filter(Boolean).join(" · "); }
function pill(text){ const s=document.createElement("span"); s.className="meta-pill"; s.textContent=text; return s; }
function setSync(text,on){ els.syncText.textContent=text; els.syncState.classList.toggle("connected",!!on); els.syncState.classList.toggle("offline",!on); }
function toast(text){ els.toast.textContent=text; els.toast.classList.add("show"); setTimeout(()=>els.toast.classList.remove("show"),1800); }
function esc(v){ return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])); }
function clone(v){ return JSON.parse(JSON.stringify(v)); }
function hash(v){ return JSON.stringify(v,(_,val)=>val); }
