(() => {
  "use strict";

  function install() {
    if (document.querySelector("#inlinePolishStyles")) return;
    const style = document.createElement("style");
    style.id = "inlinePolishStyles";
    style.textContent = `
      .day-card .day-meta{display:none!important}.activity-row{display:grid!important;grid-template-columns:88px minmax(0,1fr) 132px!important;gap:18px!important;align-items:start!important;min-height:74px!important;padding:18px 20px!important;border-color:rgba(18,38,34,.12)!important;background:#fff!important}.activity-row.selected-context,.activity-row.inline-editing-row{outline:1px solid rgba(15,143,131,.38)!important;outline-offset:1px!important;box-shadow:0 8px 22px rgba(15,143,131,.07)!important;background:#fbfffd!important}.activity-time{font-size:17px!important;font-weight:850!important;color:var(--teal-dark)!important;line-height:1.25!important}.activity-body{display:flex!important;align-items:flex-start!important;gap:8px 10px!important;flex-wrap:wrap!important;min-width:0!important}.activity-body strong{flex:1 1 100%!important;min-width:160px!important;font-size:18px!important;line-height:1.35!important;color:var(--ink)!important}.activity-body>span:not(.inline-transport-editor):not(.inline-budget-editor),.activity-body>p{flex:1 1 100%!important;margin:0!important;color:var(--muted)!important;line-height:1.4!important}.activity-row .inline-field-chip,.activity-transport-add,.activity-transport-chip{min-height:28px!important;border:0!important;border-radius:7px!important;background:#f4f8f6!important;color:#60716d!important;padding:4px 9px!important;font-size:14px!important;font-weight:760!important;box-shadow:none!important}.activity-row .inline-field-chip:hover,.activity-transport-add:hover,.activity-transport-chip:hover{background:#e8f6f2!important;color:var(--teal-dark)!important}.activity-row .inline-budget-chip{background:#fff2ee!important;color:#a73d2e!important}.activity-actions{justify-content:flex-end!important;gap:10px!important}.activity-actions button{opacity:.82!important}.inline-activity-input{min-height:34px!important;border-radius:8px!important;border-color:rgba(15,143,131,.28)!important;box-shadow:0 0 0 2px rgba(15,143,131,.06)!important}.inline-budget-editor,.inline-transport-editor{width:100%!important;display:grid!important;grid-template-columns:120px 92px minmax(120px,1fr) minmax(120px,1fr)!important;gap:8px!important}.inline-transport-editor .transport-type{grid-column:auto!important}.inline-budget-editor .budget-amount{width:120px!important}.inline-budget-editor .budget-currency{width:92px!important}.inline-empty-add{border-style:dashed!important;background:#fbfffd!important;color:#7a8985!important}.inline-empty-add::after{content:'点击添加事项';font-weight:850;color:var(--teal-dark)}.inline-empty-add{font-size:0!important}@media(max-width:780px){.activity-row{grid-template-columns:62px minmax(0,1fr) 86px!important;gap:10px!important;padding:14px!important}.activity-body strong{font-size:16px!important}.inline-budget-editor,.inline-transport-editor{grid-template-columns:1fr!important}.activity-actions{gap:6px!important}}
    `;
    document.head.append(style);
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", install, { once: true });
  else install();
})();
